/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package steam_lab7;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Crear_Usuario extends javax.swing.JFrame {
    

    /**
     * Creates new form Crear_Usuario
     */
    public Crear_Usuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //recordar borrar esto
        users.add(new Usuarios("HarlenLopez","admin","supersecreto",18,1));
    }
    public static Usuarios llamar=new Usuarios("","","",0,0);
    public static ArrayList<Usuarios> users=new ArrayList<>();
    public static int cantidadeusuarios=1;
    public static int edadCrear=0;
    public static boolean puedeAvanzar=false,puedeAvanzar1=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PasswordTextbox = new javax.swing.JTextField();
        UsuarioTextbox = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        NombreTextbox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdadTextbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Crear_usuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, -1, -1));
        jPanel1.add(PasswordTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 270, 40));

        UsuarioTextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextboxActionPerformed(evt);
            }
        });
        jPanel1.add(UsuarioTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 270, 40));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 630, -1, 50));
        jPanel1.add(NombreTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 270, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, -1, 24));
        jPanel1.add(EdadTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 550, 100, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 170, 24));

        Crear_usuario.setText("Crear Usuario");
        Crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, -1, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_usuarioActionPerformed
        // TODO add your handling code here:
        String usuarioCrear=UsuarioTextbox.getText();
        String nombreCrear=NombreTextbox.getText();
        String contraseñaCrear=PasswordTextbox.getText();
        String edad=EdadTextbox.getText();
        if(usuarioCrear.isEmpty()||nombreCrear.isEmpty()||contraseñaCrear.isEmpty()||edad.isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, llenar todos los campos.");
        }else{
        try{
            edadCrear=Integer.parseInt(edad);
            puedeAvanzar=true;
        }catch(NumberFormatException e){
            puedeAvanzar=false;
        }
        if(puedeAvanzar==true){
            //Recordar hacer una clase que busque si el usuario ya existe
            for(int indice=0;indice<users.size();indice++){
                if(users.get(indice)!=null){
                    if(users.get(indice).getUser().equals(usuarioCrear)){
                        puedeAvanzar1=false;
                        JOptionPane.showMessageDialog(null, "Usuario ya existe.");
                        break;
                    }else{
                        puedeAvanzar1=true;
                    }
                }
            }
            if(puedeAvanzar1==true){                    
            int error=0;
           
            users.add(new Usuarios(nombreCrear,usuarioCrear,contraseñaCrear,edadCrear,error));
            JOptionPane.showMessageDialog(null, "Ha creado exitosamente su cuenta.");
            cantidadeusuarios++;
            puedeAvanzar=false;
            puedeAvanzar1=false;
            
            
            this.setVisible(false);
            Login pasar = new Login();
            pasar.setVisible(true);
            
            }
        }else{
            JOptionPane.showMessageDialog(null,"Ingrese su edad en numeros enteros");
        }
    }
    }//GEN-LAST:event_Crear_usuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here: Administracion_de_usuarios pasar=new Administracion_de_usuarios();
        Login pasar = new Login();
        pasar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void UsuarioTextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear_usuario;
    private javax.swing.JTextField EdadTextbox;
    private javax.swing.JTextField NombreTextbox;
    private javax.swing.JTextField PasswordTextbox;
    private javax.swing.JTextField UsuarioTextbox;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
